---
title: "Untitled"
author: "Hugo"
date: "18/03/2022"
output: html_document
---
```{r}
library(shiny)
library(readxl)
library(MLmetrics)
library(randomForest)
library(ggplot2)
library(leaps)
library(bestglm)
library(ggfortify)
library(gridExtra)
library(dplyr)
library(reshape2)
library(ROCR)
library(pROC)
library(MASS)
library(partykit)
library(glmnet)
library(naivebayes)
```


```{r}
Tab_global <- read_excel("fichier arbre 1.xlsx", col_names = TRUE)

Tab_global <- Tab_global[,2:length(Tab_global)]

Tab_global$Sport<-as.factor(Tab_global$Sport)
Tab_global$Stab_pelv_asy= factor(Tab_global$Stab_pelv_asy)
Tab_global$Mob_inf_asy = factor(Tab_global$Mob_inf_asy)
Tab_global$Mob_sup_asy = factor(Tab_global$Mob_sup_asy)
Tab_global$Entrant = factor(Tab_global$Entrant)
Tab_global$Doul_act_MI = factor(Tab_global$Doul_act_MI)
Tab_global$Doul_act_MS = factor(Tab_global$Doul_act_MS)
#Tab_global$Doul_act_rachis = factor(Tab_global$Doul_act_rachis)
Tab_global$Blessure = factor(Tab_global$Blessure)
Tab_global$Blessure_MI = factor(Tab_global$Blessure_MI)
Tab_global$Blessure_MS = factor(Tab_global$Blessure_MS)
Tab_global$Blessure_rachis = factor(Tab_global$Blessure_rachis)
#Tab_global$Blessure_T_T = factor(Tab_global$Blessure_T_T)
Tab_global$Ancienne_blessure_MI_bin = factor(Tab_global$Ancienne_blessure_MI_bin)
Tab_global$Ancienne_blessure_MS_bin = factor(Tab_global$Ancienne_blessure_MS_bin)
Tab_global$Ancienne_blessure_rachis_bin = factor(Tab_global$Ancienne_blessure_rachis_bin)

Tab_global$Nb_bless <- as.numeric(Tab_global$Nb_bless)
#Tab_global$`Mob inf asy`<-as.numeric(Tab_global$`Mob inf asy`)
#Tab_global$`Mob sup asy`<-as.numeric(Tab_global$`Mob sup asy`)
Tab_global$Mob_inf_droite<-as.numeric(Tab_global$Mob_inf_droite)
Tab_global$Mob_inf_gauche<-as.numeric(Tab_global$Mob_inf_gauche)
Tab_global$Mob_sup_droite<-as.numeric(Tab_global$Mob_sup_droite)
Tab_global$Mob_sup_gauche<-as.numeric(Tab_global$Mob_sup_gauche)
Tab_global$Mob_inf_bil <-as.numeric(Tab_global$Mob_inf_bil)
Tab_global$Mob_sup_bil <-as.numeric(Tab_global$Mob_sup_bil)
Tab_global$Global<-as.numeric(Tab_global$Global)
#Tab_global$Blessure <- as.numeric(Tab_global$Blessure)

#Tab_global$`Stab pelv asy`<-as.numeric(Tab_global$`Stab pelv asy`)

Tab_global$Ancienne_blessure_MI <-as.numeric(Tab_global$Ancienne_blessure_MI)
Tab_global$Ancienne_blessure_MS <-as.numeric(Tab_global$Ancienne_blessure_MS)
Tab_global$Ancienne_blessure_rachis <-as.numeric(Tab_global$Ancienne_blessure_rachis)

Tab_global$Stab_pelv_droite <-as.numeric(Tab_global$Stab_pelv_droite)
Tab_global$Stab_pelv_gauche<-as.numeric(Tab_global$Stab_pelv_gauche)
Tab_global$Stab_core <-as.numeric(Tab_global$Stab_core)
Tab_global$Stab_core_scap <-as.numeric(Tab_global$Stab_core_scap)
Tab_global$Stab_scapulaire <-as.numeric(Tab_global$Stab_scapulaire)
#Tab_global$`Stab scapulaire`<-as.numeric(Tab_global$`Stab scapulaire`)

Indispo <- read_excel("Indispo.xlsx", col_names = TRUE)

Indispo$sport<-as.factor(Indispo$sport)
Indispo$zone<-as.factor(Indispo$zone)
Indispo$duree<-as.factor(Indispo$duree)
```



```{r}
summary(Indispo)
```


```{r}
mod.log.bless <- glm(Blessure ~ Sport + Entrant + Ancienne_blessure_MI_bin + Stab_core_scap + Somme_stab_pelv,data = Tab_global, family=binomial(link="logit"))

mod.log.bless.MI <- glm(Blessure_MI ~ Sport + Entrant + Ancienne_blessure_MI_bin + Stab_core_scap + Ancienne_blessure_MS_bin,data = Tab_global, family=binomial(link="logit"))

mod.log.bless.MS <- glm(Blessure_MS ~ Sport + Somme_mob_sup + Ancienne_blessure_MS_bin,data = Tab_global, family=binomial(link="logit"))

mod.log.bless.rachis <- glm(Blessure_rachis ~ Sport + Stab_core_scap + Entrant + Somme_stab_pelv + Ancienne_blessure_MI_bin,data = Tab_global, family=binomial(link="logit"))
```

```{r}

  prop
```


```{r}
ui <- fluidPage(
  titlePanel("Prediction des blessures"),
  sidebarLayout(
    sidebarPanel(
      h3("Donnees du sportif", align = "center"),
      
      selectInput(inputId = "Sport",
                  label = "Choisir le sport :",
                  choices = c("Aviron", "Baseball", "Basket","Bowling","Nat Synchro","Natation","Rugby","Savate")),
      sliderInput(inputId = "Somme_mob_inf",
                  label = "Somme mob inf :",
                  min = 0,
                  max = 8,
                  value = 4),
      
      sliderInput(inputId = "Somme_mob_sup",
                  label = "Somme mob sup :",
                  min = 0,
                  max = 4,
                  value = 2),
      sliderInput(inputId = "Somme_stab_pelv",
                  label = "Somme stab pelv :",
                  min = 0,
                  max = 6,
                  value = 3),
      sliderInput(inputId = "Stab_core_scap",
                  label = "Stab core + Scap :",
                  min = 0,
                  max = 2,
                  value = 1),
      selectInput(inputId = "Entrant",
                  label = "Entrant dans la structure :",
                  choices = c("oui", "non")),
      selectInput(inputId = "Ancienne_bless_MI_bin",
                  label = "Anciennes blessures au membres inf :",
                  choices = c("oui", "non")),
      selectInput(inputId = "Ancienne_bless_MS_bin",
                  label = "Anciennes blessures au membres sup :",
                  choices = c("oui", "non")),
    ),
    mainPanel(
      h3("Récap du sportif", align = "center"),
      tableOutput("values"),
      textOutput("proba_blessure"),
      textOutput("proba_blessure_MI"),
      fluidRow(
        column(6,plotOutput("cam_MI")),
        column(6,plotOutput("cam_MI_sport"))
        ),
      textOutput("proba_blessure_MS"),
      fluidRow(
        column(6,plotOutput("cam_MS")),
        column(6,plotOutput("cam_MS_sport"))
        ),
      textOutput("proba_blessure_rachis"),
      fluidRow(
        column(6,plotOutput("cam_Rachis")),
        column(6,plotOutput("cam_Rachis_sport"))
        ),
    )
  )
)
server <- function(input, output) {
  Indispo <- read_excel("Indispo.xlsx", col_names = TRUE)
  Indispo$sport<-as.factor(Indispo$sport)
  Indispo$zone<-as.factor(Indispo$zone)
  Indispo$duree<-as.factor(Indispo$duree)
  
  sliderValues <- reactive({
    data.frame(
      Name = c("Sport",
               "Somme mob inf",
               "Somme mob sup",
               "Somme stab pelv",
               "Stab core + pelv",
               "Entrant",
               "Anciennes blessures aux membres inf",
               "Anciennes blessures aux membres sup"),
      Value = as.character(c(input$Sport,
                             input$Somme_mob_inf,
                             input$Somme_mob_sup,
                             input$Somme_stab_pelv,
                             input$Stab_core_scap,
                             input$Entrant,
                             input$Ancienne_bless_MI_bin,
                             input$Ancienne_bless_MS_bin)),
      stringsAsFactors = TRUE)
  })
  output$values <- renderTable({
    sliderValues()
  })
  nouveau_sportif <- reactive({
    data.frame(
      Sport = input$Sport,
      Somme_mob_inf = input$Somme_mob_inf,
      Somme_mob_sup = input$Somme_mob_sup,
      Somme_stab_pelv = input$Somme_stab_pelv,
      Stab_core_scap = input$Stab_core_scap,
      Entrant = input$Entrant,
      Ancienne_blessure_MI_bin = input$Ancienne_bless_MI_bin,
      Ancienne_blessure_MS_bin = input$Ancienne_bless_MS_bin)
  })
  
  user <- reactive({
    data.frame(
      Sport = input$Sport)
  })
  
  output$proba_blessure <- renderText({
    print(paste("Probabilité d'être blessé au cours de l'année : ",predict(mod.log.bless, type = "response", newdata = nouveau_sportif())))
  })
  output$proba_blessure_MI <- renderText({
    print(paste("Probabilité d'être blessé aux membres inf : ",predict(mod.log.bless.MI, type = "response", newdata = nouveau_sportif())))
  })

  output$proba_blessure_MS <- renderText({
    print(paste("Probabilité d'être blessé aux membres sup : ",predict(mod.log.bless.MS, type = "response", newdata = nouveau_sportif())))
  })
  output$proba_blessure_rachis <- renderText({
    print(paste("Probabilité d'être blessé au rachis/tronc : ",predict(mod.log.bless.rachis, type = "response", newdata = nouveau_sportif())))
  })
  output$cam_MI <- renderPlot({
    count.MI <- data.frame(
  class = c("1 semaine ou moins", "1-3 semaines", "Plus de 3 semaines"),
  prop = c(round(dim(Indispo[which(Indispo$duree==1 & Indispo$zone=="MI"),])[1]*100/dim(Indispo[which(Indispo$zone=="MI"),])[1],1),
        round(dim(Indispo[which(Indispo$duree==2 & Indispo$zone=="MI"),])[1]*100/dim(Indispo[which(Indispo$zone=="MI"),])[1],1),
        round(dim(Indispo[which(Indispo$duree==3 & Indispo$zone=="MI"),])[1]*100/dim(Indispo[which(Indispo$zone=="MI"),])[1],1))
)

count.MI <- count.MI %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(prop) - 0.5*prop)

mycols <- c("#CCFFFF", "#66FFFF", "#0099CC")

ggplot(count.MI, aes(x = "", y = prop, fill = class)) +
  ggtitle("Indispo pour les blessures aux MI")+
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = prop), color = "black")+
  scale_fill_manual(values = mycols) +
  theme_void()
  })
  
  output$cam_MI_sport <- renderPlot({
    count.MI.sport <- data.frame(
  class = c("1 semaine ou moins", "1-3 semaines", "Plus de 3 semaines"),
  prop = c(round(dim(Indispo[which(Indispo$duree==1 & Indispo$zone=="MI" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="MI" & Indispo$sport == user()$Sport),])[1],1),
        round(dim(Indispo[which(Indispo$duree==2 & Indispo$zone=="MI" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="MI" & Indispo$sport == user()$Sport),])[1],1),
        round(dim(Indispo[which(Indispo$duree==3 & Indispo$zone=="MI" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="MI" & Indispo$sport == user()$Sport),])[1],1))
)


count.MI.sport <- count.MI.sport %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(prop) - 0.5*prop)

mycols <- c("#CCFFFF", "#66FFFF", "#0099CC")

ggplot(count.MI.sport, aes(x = "", y = prop, fill = class)) +
  ggtitle(paste("idem mais uniquement avec",user()$Sport))+
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = prop), color = "black")+
  scale_fill_manual(values = mycols) +
  theme_void()
  })
  
    output$cam_MS <- renderPlot({
    count.MS <- data.frame(
  class = c("1 semaine ou moins", "1-3 semaines", "Plus de 3 semaines"),
  prop = c(round(dim(Indispo[which(Indispo$duree==1 & Indispo$zone=="MS"),])[1]*100/dim(Indispo[which(Indispo$zone=="MS"),])[1],1),
        round(dim(Indispo[which(Indispo$duree==2 & Indispo$zone=="MS"),])[1]*100/dim(Indispo[which(Indispo$zone=="MS"),])[1],1),
        round(dim(Indispo[which(Indispo$duree==3 & Indispo$zone=="MS"),])[1]*100/dim(Indispo[which(Indispo$zone=="MS"),])[1],1))
)

count.MS <- count.MS %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(prop) - 0.5*prop)

mycols <- c("#FF9900", "#FF6600", "#FF3300")

ggplot(count.MS, aes(x = "", y = prop, fill = class)) +
  ggtitle("Indispo pour les blessures aux MS")+
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = prop), color = "black")+
  scale_fill_manual(values = mycols) +
  theme_void()
  })
    
  output$cam_MS_sport <- renderPlot({
    count.MS.sport <- data.frame(
  class = c("1 semaine ou moins", "1-3 semaines", "Plus de 3 semaines"),
  prop = c(round(dim(Indispo[which(Indispo$duree==1 & Indispo$zone=="MS" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="MS" & Indispo$sport == user()$Sport),])[1],1),
        round(dim(Indispo[which(Indispo$duree==2 & Indispo$zone=="MS" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="MS" & Indispo$sport == user()$Sport),])[1],1),
        round(dim(Indispo[which(Indispo$duree==3 & Indispo$zone=="MS" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="MS" & Indispo$sport == user()$Sport),])[1],1))
)

    count.MS.sport <- count.MS.sport %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(prop) - 0.5*prop)

mycols <- c("#FF9900", "#FF6600", "#FF3300")

ggplot(count.MS.sport, aes(x = "", y = prop, fill = class)) +
  ggtitle(paste("idem mais uniquement avec",user()$Sport))+
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = prop), color = "black")+
  scale_fill_manual(values = mycols) +
  theme_void()
  })
    
  output$cam_Rachis <- renderPlot({
    count.Rachis <- data.frame(
  class = c("1 semaine ou moins", "1-3 semaines", "Plus de 3 semaines"),
  prop = c(round(dim(Indispo[which(Indispo$duree==1 & Indispo$zone=="Rachis"),])[1]*100/dim(Indispo[which(Indispo$zone=="Rachis"),])[1],1),
        round(dim(Indispo[which(Indispo$duree==2 & Indispo$zone=="Rachis"),])[1]*100/dim(Indispo[which(Indispo$zone=="Rachis"),])[1],1),
        round(dim(Indispo[which(Indispo$duree==3 & Indispo$zone=="Rachis"),])[1]*100/dim(Indispo[which(Indispo$zone=="Rachis"),])[1],1))
)
    
count.Rachis <- count.Rachis %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(prop) - 0.5*prop)

mycols <- c("#CCFF66", "#66FF33", "#66CC33")

ggplot(count.Rachis, aes(x = "", y = prop, fill = class)) +
  ggtitle("Indispo pour les blessures au rachis/tronc")+
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = prop), color = "black")+
  scale_fill_manual(values = mycols) +
  theme_void()
  })
  
  output$cam_Rachis_sport <- renderPlot({
    count.Rachis.sport <- data.frame(
  class = c("1 semaine ou moins", "1-3 semaines", "Plus de 3 semaines"),
  prop = c(round(dim(Indispo[which(Indispo$duree==1 & Indispo$zone=="Rachis" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="Rachis" & Indispo$sport == user()$Sport),])[1],1),
        round(dim(Indispo[which(Indispo$duree==2 & Indispo$zone=="Rachis" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="Rachis" & Indispo$sport == user()$Sport),])[1],1),
        round(dim(Indispo[which(Indispo$duree==3 & Indispo$zone=="Rachis" & Indispo$sport == user()$Sport),])[1]*100/dim(Indispo[which(Indispo$zone=="Rachis" & Indispo$sport == user()$Sport),])[1],1))
)


count.Rachis.sport <- count.Rachis.sport %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(prop) - 0.5*prop)

mycols <- c("#CCFF66", "#66FF33", "#66CC33")

ggplot(count.Rachis.sport, aes(x = "", y = prop, fill = class)) +
  ggtitle(paste("idem mais uniquement avec",user()$Sport))+
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = prop), color = "black")+
  scale_fill_manual(values = mycols) +
  theme_void()
  })
}
shinyApp(ui, server)
```











